ADDPROXY=http://localhost:8001
SUBTRACTPROXY=http://localhost:8002
MULTIPLYPROXY=http://localhost:8003
DIVIDEPROXY=http://localhost:8004

COMPOSITEOPPROXY=http://localhost:8005
PROCESSORPROXY=http://localhost:8006

test-add:
	-bash -c './add.sh $(ADDPROXY)'	

test-subtract:
	-bash -c './subtract.sh $(SUBTRACTPROXY)'

test-multiply:
	-bash -c './multiply.sh $(MULTIPLYPROXY)'	

test-divide:
	-bash -c './divide.sh $(DIVIDEPROXY)'

test-compositeop:
	-bash -c './compositeop.sh $(COMPOSITEOPPROXY)'

test-processor:
	-bash -c './processor.sh $(PROCESSORPROXY)'	