PROXY=http://calculator.io

test-add:
	-bash -c './add.sh $(PROXY)'	

test-subtract:
	-bash -c './subtract.sh $(PROXY)'

test-multiply:
	-bash -c './multiply.sh $(PROXY)'	

test-divide:
	-bash -c './divide.sh $(PROXY)'

test-compositeop:
	-bash -c './compositeop.sh $(PROXY)'

test-processor:
	-bash -c './processor.sh $(PROXY)'	

test-mtprocessor:
	-bash -c './mtprocessor.sh $(PROXY)'

test-eventprocessor:
	-bash -c './eventprocessor.sh $(PROXY)'	
